name: industrial-data-collector

services:
  mongo: 
    image: mongo:8.3
    container_name: mongo-db
    restart: unless-stopped
    ports: ["27017:27017"]
    networks: ["backend"]
    volumes: ["mongo_data:/data/db"]
  
  postgres:
    image: postgres:18.4
    container_name: postgres-db
    restart: unless-stopped
    ports: ["5432:5432"]
    networks: ["backend"]
    volumes: ["postgres_data:/var/lib/postgresql"]  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 15

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports: ["8883:8883"]
    networks: ["backend"]
    volumes: 
      - "mosquitto_data:/mosquitto/data"
      - "./mosquitto/config:/mosquitto/config"
      - "./certs:/mosquitto/certs:ro"

  mqtt-pub-1:
    build: ./services
    container_name: idc-mqtt-pub-1
    restart: unless-stopped
    command: python -u -m mqtt_publisher.main
    environment:
      CLIENT_ID: pub-1
      PAIR: BTC-USD
      PUBLISH_INTERVAL: "5"
      BROKER_HOST: mosquitto
      BROKER_PORT: "8883"
      TOPIC_CATEGORY: "crypto"
      MQTT_USERNAME: publisher
      MQTT_PASSWORD: ${MQTT_PUBLISHER_PASSWORD}
      MQTT_TLS_CA: /certs/ca.crt
    depends_on: [mosquitto]
    networks: [backend]
    volumes:
      - "./certs/ca.crt:/certs/ca.crt:ro"

  mqtt-pub-2:
    build: ./services
    container_name: idc-mqtt-pub-2
    restart: unless-stopped
    command: python -u -m mqtt_publisher.main
    environment:
      CLIENT_ID: pub-2
      PAIR: ETH-USD
      PUBLISH_INTERVAL: "7"
      BROKER_HOST: mosquitto
      BROKER_PORT: "8883"
      TOPIC_CATEGORY: "crypto"
      MQTT_USERNAME: publisher
      MQTT_PASSWORD: ${MQTT_PUBLISHER_PASSWORD}
      MQTT_TLS_CA: /certs/ca.crt
    depends_on: [mosquitto]
    networks: [backend]
    volumes:
      - "./certs/ca.crt:/certs/ca.crt:ro"

  mqtt-ingest:
    build: ./services
    container_name: idc-mqtt-ingest
    restart: unless-stopped
    command: python -u -m mqtt_ingest.main
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "8883"
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: iot
      MONGO_COLLECTION: "mqtt_measurements"
      TOPIC: "telemetry/#"
      MQTT_USERNAME: ingest
      MQTT_PASSWORD: ${MQTT_INGEST_PASSWORD}
      MQTT_TLS_CA: /certs/ca.crt
    depends_on: [mosquitto, mongo]
    networks: [backend]
    volumes:
      - "./certs/ca.crt:/certs/ca.crt:ro"

  modbus-server:
    build: ./services
    container_name: idc-modbus-server
    restart: unless-stopped
    command: python -u -m modbus_server.main
    environment:
      PAIR: BTC-USD
      LISTEN_HOST: "0.0.0.0"
      UPDATE_INTERVAL: 5
    networks: [backend]

  modbus-client:
    build: ./services
    container_name: idc-modbus-client
    restart: unless-stopped
    command: python -u -m modbus_client.main
    environment:
      MODBUS_HOST: modbus-server
      MODBUS_PORT: 5020
      POLL_INTERVAL: 5
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: "iot"
      MONGO_COLLECTION: "modbus_measurements"
    networks: [backend]
    depends_on: [modbus-server, mongo]

  django:
    build: ./django_app
    container_name: idc-django
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate && 
      python manage.py createsuperuser --noinput || true && 
      python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: iot
      BROKER_HOST: mosquitto
      BROKER_PORT: "8883"
      MQTT_USERNAME: django
      MQTT_PASSWORD: ${MQTT_DJANGO_PASSWORD}
      MQTT_TLS_CA: /certs/ca.crt
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_started
      mosquitto:
        condition: service_started
      postgres:
        condition: service_healthy
    networks: [backend]
    volumes:
      - "./certs/ca.crt:/certs/ca.crt:ro"

volumes:
  mongo_data:
  postgres_data:
  mosquitto_data:

networks:
  backend:
    driver: bridge
